// Generated by CoffeeScript 1.4.0
(function() {
  var CK;

  window.CK = {};

  CK = window.CK;

  CK.getState = function(type, callback) {
    var states;
    states = new CK.Model.States();
    states.on('reset', function(ss) {
      var state;
      state = ss.find(function(s) {
        return s.get('type') === type;
      });
      return callback(state);
    });
    return states.fetch();
  };

  CK.getStateForUser = function(type, username, state_name, callback) {
    var states;
    states = new CK.Model.States();
    states.on('reset', function(ss) {
      var state;
      state = ss.find(function(s) {
        return s.get('type') === type && s.get('username') === username && s.get('state') === state_name;
      });
      return callback(state);
    });
    return states.fetch();
  };

  CK.setState = function(type, state) {
    return CK.getState(type, function(s) {
      if (s != null) {
        s = new CK.Model.State();
        s.set('type', type);
      }
      s.set('state', state);
      return s.save();
    });
  };

  CK.setStateForUser = function(type, username, state, data_obj) {
    return CK.getStateForUser(type, username, state, function(s) {
      if (s == null) {
        s = new CK.Model.State();
        s.set('type', type);
        s.set('username', username);
        s.set('state', state);
      }
      s.set('data', data_obj);
      return s.save();
    });
  };

}).call(this);
